### ISSUE TITLE
🧪 Unit Tests

### ISSUE THREAD

**Issue by GokselKUCUKSAHIN** [jellybeanci/yukine#81]
# 🧪 Unit Test Task List 📝
- [x] #88
- [x] #87
- [x] #86
    - [x] `Array<T>` prototype
        - [x] Create Unit Test for #82
        - [x] Create Unit Test for #83
        - [x] Create Unit Test for #84
        - [x] Create Unit Test for #85
        - [x] Create Unit Test for #89
        - [x] Create Unit Test for #90
        - [x] Create Unit Test for #91
        - [x] Create Unit Test for #92
        - [x] Create Unit Test for #93
        - [x] Create Unit Test for #94
        - [x] Create Unit Test for #96
        - [x] Create Unit Test for #95
        - [x] Create Unit Test for #97
        - [x] Create Unit Test for #98
        - [x] Create Unit Test for #99
        - [x] Create Unit Test for #100
        - [x] Create Unit Test for #101
        - [x] Create Unit Test for #102
        - [x] Create Unit Test for #103
        - [x] Create Unit Test for #104
        - [x] Create Unit Test for #105
        - [x] Create Unit Test for #106
        - [x] Create Unit Test for #107
        - [x] Create Unit Test for #108
        - [x] Create Unit Test for #109
        - [x] Create Unit Test for #110
        - [x] Create Unit Test for #111
        - [x] Create Unit Test for #112
        - [x] Create Unit Test for #113
        - [x] Create Unit Test for #114
        - [x] Create Unit Test for #115
        - [x] Create Unit Test for #116
        - [x] Create Unit Test for #117
        - [x] Create Unit Test for #118
        - [x] Create Unit Test for #119
        - [x] Create Unit Test for #120
        - [x] Create Unit Test for #121
        - [x] Create Unit Test for #122
        - [x] Create Unit Test for #123
        - [x] Create Unit Test for #124
        - [x] Create Unit Test for #125
        - [x] Create Unit Test for #126
        - [x] Create Unit Test for #127
        - [x] Create Unit Test for #156
        - [x] Create Unit Test for #161
        - [x] Create Unit Test for #162
        - [x] Create Unit Test for #163
        - [x] Create Unit Test for #170
        - [x] Create Unit Test for #175
    - [x] `Number` prototype
        - [x] Create Unit Test for #128
        - [x] Create Unit Test for #129
    - [x] `String` prototype
        - [x] Create Unit Test for #130
    - [x] `Math` prototype
        - [x] Create Unit Test for #165
            - [x] Create Unit Test for #131
            - [x] Create Unit Test for #132
            - [x] Create Unit Test for #133 
        - [x] Create Unit Test for #134
        - [x] Create Unit Test for #135
        - [x] Create Unit Test for #136
        - [x] Create Unit Test for #137
        - [x] Create Unit Test for #138
        - [x] Create Unit Test for #139
        - [x] Create Unit Test for #140
        - [x] Create Unit Test for #141
        - [x] Create Unit Test for #142
        - [x] Create Unit Test for #143
        - [x] Create Unit Test for #144
        - [x] Create Unit Test for #145
        - [x] Create Unit Test for #146
        - [x] Create Unit Test for #147
    - [x] `Utils`
        - [x] #151
        - [x] #153
        - [x] #154
        - [x] #155
